# This file is auto-generated by nodetool.dsl.codegen.
# Please do not edit this file manually.

# Instead, edit the node class in the source module and run the following commands to regenerate the DSL:
# nodetool package scan
# nodetool codegen

from pydantic import BaseModel, Field
import typing
from typing import Any
import nodetool.metadata.types
import nodetool.metadata.types as types
from nodetool.dsl.graph import GraphNode, SingleOutputGraphNode

import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.calendar
from nodetool.workflows.base_node import BaseNode


class CreateCalendarEvent(SingleOutputGraphNode[typing.Any], GraphNode[typing.Any]):
    """

    Create a new event in Apple Calendar via AppleScript
    calendar, automation, macos, productivity

    Use cases:
    - Automate event creation
    - Schedule meetings programmatically
    - Create recurring events
    """

    title: str | OutputHandle[str] = connect_field(
        default="New Event", description="Title of the calendar event"
    )
    start_date: types.Datetime | OutputHandle[types.Datetime] = connect_field(
        default=types.Datetime(
            type="datetime",
            year=0,
            month=0,
            day=0,
            hour=0,
            minute=0,
            second=0,
            microsecond=0,
            tzinfo="UTC",
            utc_offset=0,
        ),
        description="Start date and time of the event",
    )
    end_date: types.Datetime | OutputHandle[types.Datetime] = connect_field(
        default=types.Datetime(
            type="datetime",
            year=0,
            month=0,
            day=0,
            hour=0,
            minute=0,
            second=0,
            microsecond=0,
            tzinfo="UTC",
            utc_offset=0,
        ),
        description="End date and time of the event",
    )
    calendar_name: str | OutputHandle[str] = connect_field(
        default="Calendar", description="Name of the calendar"
    )
    location: str | OutputHandle[str] = connect_field(
        default="", description="Location of the event"
    )
    description: str | OutputHandle[str] = connect_field(
        default="", description="Description/notes for the event"
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.calendar.CreateCalendarEvent

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.calendar
from nodetool.workflows.base_node import BaseNode


class ListCalendarEvents(
    SingleOutputGraphNode[list[types.CalendarEvent]],
    GraphNode[list[types.CalendarEvent]],
):
    """

    List events from Apple Calendar within a specified date range
    calendar, automation, macos, productivity

    Use cases:
    - Retrieve upcoming events
    - Check schedule availability
    - Export calendar events
    """

    days_back: int | OutputHandle[int] = connect_field(
        default=0, description="Number of days to look back from today"
    )
    days_forward: int | OutputHandle[int] = connect_field(
        default=7, description="Number of days to look forward from today"
    )
    calendar_name: str | OutputHandle[str] = connect_field(
        default="Calendar", description="Name of the calendar to search"
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.calendar.ListCalendarEvents

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()
