# This file is auto-generated by nodetool.dsl.codegen.
# Please do not edit this file manually.

# Instead, edit the node class in the source module and run the following commands to regenerate the DSL:
# nodetool package scan
# nodetool codegen

from pydantic import BaseModel, Field
import typing
from typing import Any
import nodetool.metadata.types
import nodetool.metadata.types as types
from nodetool.dsl.graph import GraphNode, SingleOutputGraphNode

import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.clipboard
from nodetool.workflows.base_node import BaseNode


class GetClipboardImage(
    SingleOutputGraphNode[types.ImageRef], GraphNode[types.ImageRef]
):
    """

    Read an image from the macOS clipboard (NSPasteboard) and return it as an ImageRef.
    clipboard, macos, automation, media

    Use cases:
    - Copy an image/screenshot and run vision/OCR downstream
    - Quick “copy image → caption → paste alt text” flows
    - Route clipboard images into Notes/Files shortcuts
    """

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.clipboard.GetClipboardImage

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.clipboard
from nodetool.workflows.base_node import BaseNode


class GetClipboardText(SingleOutputGraphNode[types.TextRef], GraphNode[types.TextRef]):
    """

    Read plain text from the macOS clipboard (NSPasteboard).
    clipboard, macos, automation, productivity

    Use cases:
    - “Copy → summarize → paste back” workflows
    - Use current selection as agent input
    - Lightweight handoff between apps and nodetool
    """

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.clipboard.GetClipboardText

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.clipboard
from nodetool.workflows.base_node import BaseNode


class SetClipboardImage(SingleOutputGraphNode[bool], GraphNode[bool]):
    """

    Write an image to the macOS clipboard (NSPasteboard).
    clipboard, macos, automation, media

    Use cases:
    - Put a generated/processed image on the clipboard for quick paste
    - Copy charts/visualizations into Keynote/Slack/etc.
    - Human review loop: generate image → copy → paste somewhere
    """

    image: types.ImageRef | OutputHandle[types.ImageRef] = connect_field(
        default=PydanticUndefined, description="Image to put on the clipboard"
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.clipboard.SetClipboardImage

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.clipboard
from nodetool.workflows.base_node import BaseNode


class SetClipboardText(SingleOutputGraphNode[bool], GraphNode[bool]):
    """

    Write plain text to the macOS clipboard (NSPasteboard).
    clipboard, macos, automation, productivity

    Use cases:
    - Put an LLM result on the clipboard for quick paste
    - Provide human-in-the-loop editing via copy/paste
    - Copy generated commands/snippets into other apps
    """

    text: str | OutputHandle[str] = connect_field(
        default="", description="Text to put on the clipboard"
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.clipboard.SetClipboardText

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()
