# This file is auto-generated by nodetool.dsl.codegen.
# Please do not edit this file manually.

# Instead, edit the node class in the source module and run the following commands to regenerate the DSL:
# nodetool package scan
# nodetool codegen

from pydantic import BaseModel, Field
import typing
from typing import Any
import nodetool.metadata.types
import nodetool.metadata.types as types
from nodetool.dsl.graph import GraphNode, SingleOutputGraphNode

import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.contacts
from nodetool.workflows.base_node import BaseNode


class GetContactByIdentifier(SingleOutputGraphNode[dict], GraphNode[dict]):
    """

    Fetch a specific macOS Contact by identifier (CNContactStore).
    contacts, macos, automation, retrieval

    Use cases:
    - Round-trip: SearchContacts → pick identifier → fetch full details
    - Store a stable reference to a person in a workflow
    """

    identifier: str | OutputHandle[str] = connect_field(
        default="", description="CNContact identifier"
    )
    include_emails: bool | OutputHandle[bool] = connect_field(
        default=True, description="Include email addresses"
    )
    include_phones: bool | OutputHandle[bool] = connect_field(
        default=True, description="Include phone numbers"
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.contacts.GetContactByIdentifier

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.contacts
from nodetool.workflows.base_node import BaseNode


class SearchContacts(SingleOutputGraphNode[list[dict]], GraphNode[list[dict]]):
    """

    Search macOS Contacts using the Contacts framework (CNContactStore).
    contacts, macos, automation, retrieval

    Use cases:
    - Resolve a human name to emails/phone numbers before messaging
    - Build “who should I notify?” flows for agents
    - Enrich workflow context with contact details
    """

    query: str | OutputHandle[str] = connect_field(
        default="", description="Name/email/phone substring to search"
    )
    limit: int | OutputHandle[int] = connect_field(
        default=10, description="Maximum contacts to return"
    )
    include_emails: bool | OutputHandle[bool] = connect_field(
        default=True, description="Include email addresses"
    )
    include_phones: bool | OutputHandle[bool] = connect_field(
        default=True, description="Include phone numbers"
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.contacts.SearchContacts

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()
