# This file is auto-generated by nodetool.dsl.codegen.
# Please do not edit this file manually.

# Instead, edit the node class in the source module and run the following commands to regenerate the DSL:
# nodetool package scan
# nodetool codegen

from pydantic import BaseModel, Field
import typing
from typing import Any
import nodetool.metadata.types
import nodetool.metadata.types as types
from nodetool.dsl.graph import GraphNode, SingleOutputGraphNode

import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.dictionary
from nodetool.workflows.base_node import BaseNode


class SearchDictionary(SingleOutputGraphNode[list[str]], GraphNode[list[str]]):
    """

    Search macOS Dictionary.app using Dictionary Services API
    dictionary, automation, macos, reference

    Use cases:
    - Look up word definitions programmatically
    - Check spelling and usage
    - Access dictionary content in workflows
    """

    term: str | OutputHandle[str] = connect_field(
        default="", description="Word or phrase to look up in the dictionary"
    )
    max_results: int | OutputHandle[int] = connect_field(
        default=1, description="Maximum number of definitions to return"
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.dictionary.SearchDictionary

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()
