# This file is auto-generated by nodetool.dsl.codegen.
# Please do not edit this file manually.

# Instead, edit the node class in the source module and run the following commands to regenerate the DSL:
# nodetool package scan
# nodetool codegen

from pydantic import BaseModel, Field
import typing
from typing import Any
import nodetool.metadata.types
import nodetool.metadata.types as types
from nodetool.dsl.graph import GraphNode, SingleOutputGraphNode

import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.finder
from nodetool.workflows.base_node import BaseNode


class GetDesktopPath(SingleOutputGraphNode[str], GraphNode[str]):
    """

    Get the path to the user's Desktop folder.
    finder, paths, macos, automation

    Use cases:
    - Save workflow outputs to Desktop for easy access
    - Reference common user folders
    - Cross-user compatible path resolution
    """

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.finder.GetDesktopPath

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.finder
from nodetool.workflows.base_node import BaseNode


class GetDocumentsPath(SingleOutputGraphNode[str], GraphNode[str]):
    """

    Get the path to the user's Documents folder.
    finder, paths, macos, automation

    Use cases:
    - Save important workflow outputs to Documents
    - Access user documents for processing
    - Cross-user compatible path resolution
    """

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.finder.GetDocumentsPath

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.finder
from nodetool.workflows.base_node import BaseNode


class GetDownloadsPath(SingleOutputGraphNode[str], GraphNode[str]):
    """

    Get the path to the user's Downloads folder.
    finder, paths, macos, automation

    Use cases:
    - Process newly downloaded files
    - Monitor downloads folder for automation triggers
    - Save workflow outputs to Downloads
    """

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.finder.GetDownloadsPath

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.finder
from nodetool.workflows.base_node import BaseNode


class GetFinderTag(SingleOutputGraphNode[int], GraphNode[int]):
    """

    Get the color tag of a file or folder in Finder.
    finder, tags, macos, automation

    Use cases:
    - Check if a file has been processed (tagged)
    - Filter files by tag status
    - Read existing organization for workflows
    """

    path: str | OutputHandle[str] = connect_field(
        default="", description="Path to the file or folder"
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.finder.GetFinderTag

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.finder
from nodetool.workflows.base_node import BaseNode


class GetFrontFinderWindow(SingleOutputGraphNode[str], GraphNode[str]):
    """

    Get the path of the frontmost Finder window's folder.
    finder, navigation, macos, automation

    Use cases:
    - Know user's current working directory in Finder
    - Context-aware file operations
    - Save files to the currently viewed folder
    """

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.finder.GetFrontFinderWindow

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.finder
from nodetool.workflows.base_node import BaseNode


class GetSelectedFinderItems(SingleOutputGraphNode[list[str]], GraphNode[list[str]]):
    """

    Get the paths of currently selected items in Finder.
    finder, files, macos, automation

    Use cases:
    - Process user-selected files in workflows
    - Get context for "right-click" style automations
    - Build on user's current file selection
    """

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.finder.GetSelectedFinderItems

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.finder
from nodetool.workflows.base_node import BaseNode


class MoveToTrash(SingleOutputGraphNode[bool], GraphNode[bool]):
    """

    Move a file or folder to the Trash.
    finder, files, macos, automation

    Use cases:
    - Clean up temporary files after processing
    - Safe deletion with recovery option
    - Batch file cleanup workflows
    """

    path: str | OutputHandle[str] = connect_field(
        default="", description="Path to the file or folder to trash"
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.finder.MoveToTrash

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.finder
from nodetool.workflows.base_node import BaseNode


class OpenFinderWindow(SingleOutputGraphNode[bool], GraphNode[bool]):
    """

    Open a new Finder window at the specified path.
    finder, navigation, macos, automation

    Use cases:
    - Open folder for user review
    - Navigate to workflow output directory
    - Set up workspace windows
    """

    path: str | OutputHandle[str] = connect_field(
        default="~", description="Path to open (defaults to home directory)"
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.finder.OpenFinderWindow

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.finder
from nodetool.workflows.base_node import BaseNode


class RevealInFinder(SingleOutputGraphNode[bool], GraphNode[bool]):
    """

    Reveal a file or folder in Finder (opens containing folder and selects item).
    finder, files, macos, automation

    Use cases:
    - Show user where a processed file was saved
    - Navigate to workflow output location
    - Highlight important files for review
    """

    path: str | OutputHandle[str] = connect_field(
        default="", description="Path to the file or folder to reveal"
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.finder.RevealInFinder

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.finder
from nodetool.workflows.base_node import BaseNode


class SetFinderTag(SingleOutputGraphNode[bool], GraphNode[bool]):
    """

    Set a color tag on a file or folder in Finder.
    finder, tags, macos, automation

    Use cases:
    - Mark processed files for easy identification
    - Categorize files by workflow status
    - Visual organization of workflow outputs
    """

    FinderTag: typing.ClassVar[type] = nodetool.nodes.apple.finder.FinderTag

    path: str | OutputHandle[str] = connect_field(
        default="", description="Path to the file or folder"
    )
    tag: nodetool.nodes.apple.finder.FinderTag = Field(
        default=nodetool.nodes.apple.finder.FinderTag.NONE,
        description="Tag color to apply",
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.finder.SetFinderTag

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()
