# This file is auto-generated by nodetool.dsl.codegen.
# Please do not edit this file manually.

# Instead, edit the node class in the source module and run the following commands to regenerate the DSL:
# nodetool package scan
# nodetool codegen

from pydantic import BaseModel, Field
import typing
from typing import Any
import nodetool.metadata.types
import nodetool.metadata.types as types
from nodetool.dsl.graph import GraphNode, SingleOutputGraphNode

import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.mail
from nodetool.workflows.base_node import BaseNode


class CreateMailDraft(SingleOutputGraphNode[bool], GraphNode[bool]):
    """

    Create a new email draft in Apple Mail (does not send).
    mail, email, macos, automation

    Use cases:
    - Prepare emails for human review before sending
    - Create bulk email drafts from workflow data
    - Set up scheduled email preparation
    """

    to: str | OutputHandle[str] = connect_field(
        default="", description="Recipient email address(es), comma-separated"
    )
    subject: str | OutputHandle[str] = connect_field(
        default="", description="Email subject line"
    )
    body: str | OutputHandle[str] = connect_field(
        default="", description="Email body content"
    )
    cc: str | OutputHandle[str] = connect_field(
        default="", description="CC recipients, comma-separated"
    )
    bcc: str | OutputHandle[str] = connect_field(
        default="", description="BCC recipients, comma-separated"
    )
    visible: bool | OutputHandle[bool] = connect_field(
        default=True, description="Show the draft window to the user"
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.mail.CreateMailDraft

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.mail
from nodetool.workflows.base_node import BaseNode


class GetSelectedMailMessages(SingleOutputGraphNode[list[dict]], GraphNode[list[dict]]):
    """

    Get information about currently selected messages in Mail.
    mail, email, macos, automation

    Use cases:
    - Process user-selected emails in workflows
    - Extract content from selected emails
    - Build email-based automation triggers
    """

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.mail.GetSelectedMailMessages

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.mail
from nodetool.workflows.base_node import BaseNode


class GetUnreadMailCount(SingleOutputGraphNode[int], GraphNode[int]):
    """

    Get the count of unread emails in Mail.
    mail, email, macos, automation

    Use cases:
    - Check for new emails in workflows
    - Trigger actions based on unread count
    - Monitor inbox status
    """

    mailbox: str | OutputHandle[str] = connect_field(
        default="INBOX", description="Mailbox name to check (default: INBOX)"
    )
    account: str | OutputHandle[str] = connect_field(
        default="", description="Account name (optional, uses first if empty)"
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.mail.GetUnreadMailCount

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.mail
from nodetool.workflows.base_node import BaseNode


class ListMailAccounts(SingleOutputGraphNode[list[str]], GraphNode[list[str]]):
    """

    List all configured email accounts in Mail.
    mail, email, macos, automation

    Use cases:
    - Discover available accounts for sending
    - Select account for email operations
    - Multi-account email workflows
    """

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.mail.ListMailAccounts

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.mail
from nodetool.workflows.base_node import BaseNode


class SearchMails(SingleOutputGraphNode[list[dict]], GraphNode[list[dict]]):
    """

    Search and list emails from Apple Mail with flexible filtering.
    mail, email, macos, automation, search

    Use cases:
    - Find emails matching specific criteria
    - List recent emails from a specific sender
    - Filter emails by subject or content
    - Get unread emails from a mailbox
    """

    mailbox: str | OutputHandle[str] = connect_field(
        default="INBOX", description="Mailbox name to search (default: INBOX)"
    )
    account: str | OutputHandle[str] = connect_field(
        default="", description="Account name (optional, searches all if empty)"
    )
    subject_contains: str | OutputHandle[str] = connect_field(
        default="", description="Filter emails where subject contains this text"
    )
    sender_contains: str | OutputHandle[str] = connect_field(
        default="", description="Filter emails where sender contains this text"
    )
    unread_only: bool | OutputHandle[bool] = connect_field(
        default=False, description="Only return unread emails"
    )
    limit: int | OutputHandle[int] = connect_field(
        default=50, description="Maximum number of emails to return"
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.mail.SearchMails

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.mail
from nodetool.workflows.base_node import BaseNode


class SendMail(SingleOutputGraphNode[bool], GraphNode[bool]):
    """

    Send an email via Apple Mail.
    mail, email, macos, automation

    Use cases:
    - Send automated notifications
    - Complete email workflows
    - Alert on workflow completion

    Note: This will actually send an email. Use CreateMailDraft for drafts.
    """

    to: str | OutputHandle[str] = connect_field(
        default="", description="Recipient email address(es), comma-separated"
    )
    subject: str | OutputHandle[str] = connect_field(
        default="", description="Email subject line"
    )
    body: str | OutputHandle[str] = connect_field(
        default="", description="Email body content"
    )
    from_account: str | OutputHandle[str] = connect_field(
        default="", description="Account to send from (optional, uses default)"
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.mail.SendMail

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()
