# This file is auto-generated by nodetool.dsl.codegen.
# Please do not edit this file manually.

# Instead, edit the node class in the source module and run the following commands to regenerate the DSL:
# nodetool package scan
# nodetool codegen

from pydantic import BaseModel, Field
import typing
from typing import Any
import nodetool.metadata.types
import nodetool.metadata.types as types
from nodetool.dsl.graph import GraphNode, SingleOutputGraphNode

import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.messages
from nodetool.workflows.base_node import BaseNode


class SendMessage(SingleOutputGraphNode[typing.Any], GraphNode[typing.Any]):
    """

    Send messages using macOS Messages.app via AppleScript
    messages, imessage, automation, macos, communication

    Use cases:
    - Send automated notifications via iMessage
    - Integrate messaging into workflows
    - Send workflow results to yourself or others
    """

    recipient: str | OutputHandle[str] = connect_field(
        default="",
        description="Phone number, email, or contact name to send message to",
    )
    text: str | OutputHandle[str] = connect_field(
        default="", description="Message content to send"
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.messages.SendMessage

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()
