# This file is auto-generated by nodetool.dsl.codegen.
# Please do not edit this file manually.

# Instead, edit the node class in the source module and run the following commands to regenerate the DSL:
# nodetool package scan
# nodetool codegen

from pydantic import BaseModel, Field
import typing
from typing import Any
import nodetool.metadata.types
import nodetool.metadata.types as types
from nodetool.dsl.graph import GraphNode, SingleOutputGraphNode

import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.music
from nodetool.workflows.base_node import BaseNode


class GetCurrentTrack(SingleOutputGraphNode[dict], GraphNode[dict]):
    """

    Get information about the currently playing track in Apple Music.
    music, media, macos, automation

    Use cases:
    - Log what's playing during workflow execution
    - Create "now playing" notifications
    - Build music-aware workflows
    """

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.music.GetCurrentTrack

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.music
from nodetool.workflows.base_node import BaseNode


class GetMusicPlayerState(SingleOutputGraphNode[str], GraphNode[str]):
    """

    Get the current player state (playing, paused, stopped) of Apple Music.
    music, media, macos, automation

    Use cases:
    - Check if music is playing before starting TTS
    - Resume music after pause in workflow
    - Monitor playback status
    """

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.music.GetMusicPlayerState

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.music
from nodetool.workflows.base_node import BaseNode


class GetMusicVolume(SingleOutputGraphNode[int], GraphNode[int]):
    """

    Get the current Apple Music app volume.
    music, media, macos, automation

    Use cases:
    - Save volume before adjustment
    - Monitor music volume levels
    """

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.music.GetMusicVolume

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.music
from nodetool.workflows.base_node import BaseNode


class MusicControl(SingleOutputGraphNode[bool], GraphNode[bool]):
    """

    Control Apple Music playback (play, pause, stop, next, previous).
    music, media, macos, automation

    Use cases:
    - Pause music during speech synthesis
    - Create playlist automation workflows
    - Remote control music from mobile workflows
    """

    PlayerState: typing.ClassVar[type] = nodetool.nodes.apple.music.PlayerState

    action: nodetool.nodes.apple.music.PlayerState = Field(
        default=nodetool.nodes.apple.music.PlayerState.PLAY,
        description="Playback action to perform",
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.music.MusicControl

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.music
from nodetool.workflows.base_node import BaseNode


class PlayTrackById(SingleOutputGraphNode[bool], GraphNode[bool]):
    """

    Play a specific track by its Music library ID.
    music, media, macos, automation

    Use cases:
    - Play a specific song from search results
    - Create precise playlist automations
    - Resume a specific track
    """

    track_id: str | OutputHandle[str] = connect_field(
        default="", description="Music track ID to play"
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.music.PlayTrackById

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.music
from nodetool.workflows.base_node import BaseNode


class SearchMusic(SingleOutputGraphNode[list[dict]], GraphNode[list[dict]]):
    """

    Search for tracks in Apple Music library.
    music, search, macos, automation

    Use cases:
    - Find songs to play by name
    - Build music discovery workflows
    - Create dynamic playlists
    """

    query: str | OutputHandle[str] = connect_field(
        default="", description="Search query for track name/artist"
    )
    limit: int | OutputHandle[int] = connect_field(
        default=10, description="Maximum results to return"
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.music.SearchMusic

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.music
from nodetool.workflows.base_node import BaseNode


class SetMusicVolume(SingleOutputGraphNode[bool], GraphNode[bool]):
    """

    Set the Apple Music app volume (independent of system volume).
    music, media, macos, automation

    Use cases:
    - Lower music volume before TTS
    - Fade music volume in workflows
    - Per-app volume control
    """

    volume: int | OutputHandle[int] = connect_field(
        default=50, description="Volume level (0-100)"
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.music.SetMusicVolume

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()
