# This file is auto-generated by nodetool.dsl.codegen.
# Please do not edit this file manually.

# Instead, edit the node class in the source module and run the following commands to regenerate the DSL:
# nodetool package scan
# nodetool codegen

from pydantic import BaseModel, Field
import typing
from typing import Any
import nodetool.metadata.types
import nodetool.metadata.types as types
from nodetool.dsl.graph import GraphNode, SingleOutputGraphNode

import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.network
from nodetool.workflows.base_node import BaseNode


class GetLocalIP(SingleOutputGraphNode[str], GraphNode[str]):
    """

    Get the local (LAN) IP address of this machine.
    network, ip, macos, automation

    Use cases:
    - Find local IP for network services
    - Set up local device communication
    - Network configuration workflows
    """

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.network.GetLocalIP

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.network
from nodetool.workflows.base_node import BaseNode


class GetPublicIP(SingleOutputGraphNode[str], GraphNode[str]):
    """

    Get the public IP address of this machine.
    network, ip, macos, automation

    Use cases:
    - Log external IP for remote access setup
    - Monitor IP changes
    - Network diagnostics
    """

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.network.GetPublicIP

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.network
from nodetool.workflows.base_node import BaseNode


class GetWiFiStatus(SingleOutputGraphNode[dict], GraphNode[dict]):
    """

    Get the current WiFi connection status and network info.
    network, wifi, macos, automation

    Use cases:
    - Check connectivity before network-dependent workflows
    - Monitor network changes
    - Log network info for troubleshooting
    """

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.network.GetWiFiStatus

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.network
from nodetool.workflows.base_node import BaseNode


class PingHost(SingleOutputGraphNode[dict], GraphNode[dict]):
    """

    Ping a host to check network connectivity.
    network, ping, macos, automation

    Use cases:
    - Check if a server is reachable
    - Network health monitoring
    - Conditional workflows based on connectivity
    """

    host: str | OutputHandle[str] = connect_field(
        default="", description="Hostname or IP address to ping"
    )
    count: int | OutputHandle[int] = connect_field(
        default=1, description="Number of ping packets"
    )
    timeout: int | OutputHandle[int] = connect_field(
        default=5, description="Timeout in seconds"
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.network.PingHost

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()
