# This file is auto-generated by nodetool.dsl.codegen.
# Please do not edit this file manually.

# Instead, edit the node class in the source module and run the following commands to regenerate the DSL:
# nodetool package scan
# nodetool codegen

from pydantic import BaseModel, Field
import typing
from typing import Any
import nodetool.metadata.types
import nodetool.metadata.types as types
from nodetool.dsl.graph import GraphNode, SingleOutputGraphNode

import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.notes
from nodetool.workflows.base_node import BaseNode


class CreateNote(SingleOutputGraphNode[typing.Any], GraphNode[typing.Any]):
    """

    Create a new note in Apple Notes via AppleScript
    notes, automation, macos, productivity

    Use cases:
    - Automatically save information to Notes
    - Create documentation or records
    - Save workflow outputs as notes
    """

    title: str | OutputHandle[str] = connect_field(
        default="", description="Title of the note"
    )
    body: str | OutputHandle[str] = connect_field(
        default="", description="Content of the note"
    )
    folder: str | OutputHandle[str] = connect_field(
        default="Notes", description="Notes folder to save to"
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.notes.CreateNote

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.notes
from nodetool.workflows.base_node import BaseNode


class ReadNotes(SingleOutputGraphNode[list[dict]], GraphNode[list[dict]]):
    """
    Read notes from Apple Notes via AppleScript
    """

    note_limit: int | OutputHandle[int] = connect_field(
        default=10, description="Maximum number of notes to export"
    )
    note_limit_per_folder: int | OutputHandle[int] = connect_field(
        default=10, description="Maximum notes per folder"
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.notes.ReadNotes

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()
