# This file is auto-generated by nodetool.dsl.codegen.
# Please do not edit this file manually.

# Instead, edit the node class in the source module and run the following commands to regenerate the DSL:
# nodetool package scan
# nodetool codegen

from pydantic import BaseModel, Field
import typing
from typing import Any
import nodetool.metadata.types
import nodetool.metadata.types as types
from nodetool.dsl.graph import GraphNode, SingleOutputGraphNode

import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.notifications
from nodetool.workflows.base_node import BaseNode


class PostNotification(SingleOutputGraphNode[bool], GraphNode[bool]):
    """

    Post a macOS Notification Center notification via AppleScript (`display notification`).
    notifications, macos, automation, productivity

    Use cases:
    - Notify when a workflow finishes
    - Surface an agent’s result without switching apps
    - Provide lightweight progress/status updates
    """

    title: str | OutputHandle[str] = connect_field(
        default="Nodetool", description="Notification title"
    )
    subtitle: str | OutputHandle[str] = connect_field(
        default="", description="Notification subtitle"
    )
    message: str | OutputHandle[str] = connect_field(
        default="", description="Notification message body"
    )
    sound_name: str | OutputHandle[str] = connect_field(
        default="",
        description="Optional sound name (e.g. 'Glass'); empty means no sound",
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.notifications.PostNotification

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()
