# This file is auto-generated by nodetool.dsl.codegen.
# Please do not edit this file manually.

# Instead, edit the node class in the source module and run the following commands to regenerate the DSL:
# nodetool package scan
# nodetool codegen

from pydantic import BaseModel, Field
import typing
from typing import Any
import nodetool.metadata.types
import nodetool.metadata.types as types
from nodetool.dsl.graph import GraphNode, SingleOutputGraphNode

import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.photos
from nodetool.workflows.base_node import BaseNode


class AddPhotoToAlbum(SingleOutputGraphNode[bool], GraphNode[bool]):
    """

    Add a photo to an existing album in Apple Photos.
    photos, albums, macos, automation

    Use cases:
    - Move photos to specific albums after import
    - Organize photos by project or category
    - Build automated photo organization workflows
    """

    photo_id: str | OutputHandle[str] = connect_field(
        default="", description="ID of photo to add to album"
    )
    album_name: str | OutputHandle[str] = connect_field(
        default="", description="Name of the target album"
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.photos.AddPhotoToAlbum

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.photos
from nodetool.workflows.base_node import BaseNode


class CreatePhotosAlbum(SingleOutputGraphNode[bool], GraphNode[bool]):
    """

    Create a new album in Apple Photos.
    photos, albums, macos, automation

    Use cases:
    - Organize workflow outputs into new albums
    - Set up album structure for imports
    - Create project-specific photo collections
    """

    name: str | OutputHandle[str] = connect_field(
        default="", description="Name for the new album"
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.photos.CreatePhotosAlbum

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.photos
from nodetool.workflows.base_node import BaseNode


class GetPhotosAlbums(SingleOutputGraphNode[list[str]], GraphNode[list[str]]):
    """

    List all albums in Apple Photos.
    photos, albums, macos, automation

    Use cases:
    - Discover albums for import targets
    - List albums for user selection
    - Build album-aware workflows
    """

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.photos.GetPhotosAlbums

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.photos
from nodetool.workflows.base_node import BaseNode


class GetPhotosInAlbum(SingleOutputGraphNode[list[dict]], GraphNode[list[dict]]):
    """

    Get all photos from a specific album in Apple Photos.
    photos, albums, macos, automation

    Use cases:
    - List photos in specific albums
    - Process photos from particular collections
    - Build album-based workflows
    """

    album_name: str | OutputHandle[str] = connect_field(
        default="", description="Name of the album to get photos from"
    )
    limit: int | OutputHandle[int] = connect_field(
        default=50, description="Maximum number of photos to return"
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.photos.GetPhotosInAlbum

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.photos
from nodetool.workflows.base_node import BaseNode


class GetRecentPhotos(SingleOutputGraphNode[list[dict]], GraphNode[list[dict]]):
    """

    Get file paths to the most recent photos in Photos library.
    photos, media, macos, automation

    Use cases:
    - Process latest photos in workflows
    - Quick access to recent camera imports
    - Photo-based automation triggers

    Note: Photos must be exported to access actual files.
    """

    limit: int | OutputHandle[int] = connect_field(
        default=10, description="Number of recent photos"
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.photos.GetRecentPhotos

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.photos
from nodetool.workflows.base_node import BaseNode


class ImportToAlbum(SingleOutputGraphNode[bool], GraphNode[bool]):
    """

    Import an image directly into a specific album in Apple Photos.
    photos, media, macos, automation

    Use cases:
    - Import and organize in one step
    - Send workflow outputs to specific albums
    - Build streamlined photo import workflows
    """

    image: types.ImageRef | OutputHandle[types.ImageRef] = connect_field(
        default=types.ImageRef(
            type="image", uri="", asset_id=None, data=None, metadata=None
        ),
        description="Image to import",
    )
    album_name: str | OutputHandle[str] = connect_field(
        default="", description="Album name to import into"
    )
    skip_duplicate: bool | OutputHandle[bool] = connect_field(
        default=True, description="Skip if a duplicate exists in Photos"
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.photos.ImportToAlbum

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.photos
from nodetool.workflows.base_node import BaseNode


class ImportToPhotos(SingleOutputGraphNode[bool], GraphNode[bool]):
    """

    Import an image into Apple Photos.
    photos, media, macos, automation

    Use cases:
    - Save generated images to Photos library
    - Archive processed images
    - Organize workflow outputs in Photos albums
    """

    image: types.ImageRef | OutputHandle[types.ImageRef] = connect_field(
        default=types.ImageRef(
            type="image", uri="", asset_id=None, data=None, metadata=None
        ),
        description="Image to import",
    )
    skip_duplicate: bool | OutputHandle[bool] = connect_field(
        default=True, description="Skip if a duplicate exists in Photos"
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.photos.ImportToPhotos

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()
