# This file is auto-generated by nodetool.dsl.codegen.
# Please do not edit this file manually.

# Instead, edit the node class in the source module and run the following commands to regenerate the DSL:
# nodetool package scan
# nodetool codegen

from pydantic import BaseModel, Field
import typing
from typing import Any
import nodetool.metadata.types
import nodetool.metadata.types as types
from nodetool.dsl.graph import GraphNode, SingleOutputGraphNode

import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.reminders
from nodetool.workflows.base_node import BaseNode


class CreateReminder(SingleOutputGraphNode[typing.Any], GraphNode[typing.Any]):
    """

    Create reminders using macOS Reminders.app via PyObjC
    reminders, automation, macos, productivity
    """

    title: str | OutputHandle[str] = connect_field(
        default="", description="Title of the reminder"
    )
    due_date: types.Datetime | OutputHandle[types.Datetime] = connect_field(
        default=types.Datetime(
            type="datetime",
            year=0,
            month=0,
            day=0,
            hour=0,
            minute=0,
            second=0,
            microsecond=0,
            tzinfo="UTC",
            utc_offset=0,
        ),
        description="Due date for the reminder",
    )
    list_name: str | OutputHandle[str] = connect_field(
        default="Reminders", description="Name of the reminders list"
    )
    notes: str | OutputHandle[str] = connect_field(
        default="", description="Additional notes for the reminder"
    )
    priority: int | OutputHandle[int] = connect_field(
        default=0, description="Priority (0-5)"
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.reminders.CreateReminder

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()
