# This file is auto-generated by nodetool.dsl.codegen.
# Please do not edit this file manually.

# Instead, edit the node class in the source module and run the following commands to regenerate the DSL:
# nodetool package scan
# nodetool codegen

from pydantic import BaseModel, Field
import typing
from typing import Any
import nodetool.metadata.types
import nodetool.metadata.types as types
from nodetool.dsl.graph import GraphNode, SingleOutputGraphNode

import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.safari
from nodetool.workflows.base_node import BaseNode


class GetFrontSafariTab(SingleOutputGraphNode[dict], GraphNode[dict]):
    """

    Get URL/title of the front tab in Safari via AppleScript.
    safari, browser, macos, automation

    Use cases:
    - Summarize what you're currently reading
    - Save current page into Notes/Reminders
    - Route the active URL into download/scrape workflows
    """

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.safari.GetFrontSafariTab

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.safari
from nodetool.workflows.base_node import BaseNode


class OpenSafariURL(SingleOutputGraphNode[bool], GraphNode[bool]):
    """

    Open a URL in Safari via AppleScript.
    safari, browser, macos, automation

    Use cases:
    - Open links from an agent step
    - Jump to a search result for human verification
    - Bring Safari to the foreground on demand
    """

    url: str | OutputHandle[str] = connect_field(
        default="", description="URL to open in Safari"
    )
    activate: bool | OutputHandle[bool] = connect_field(
        default=True, description="Bring Safari to the foreground"
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.safari.OpenSafariURL

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.safari
from nodetool.workflows.base_node import BaseNode


class SafariPageText(SingleOutputGraphNode[types.TextRef], GraphNode[types.TextRef]):
    """

    Extract visible page text from the front Safari tab (via injected JavaScript).
    safari, browser, macos, automation

    Use cases:
    - Summarize an article without copy/paste
    - Feed page content into retrieval/notes pipelines
    - Create “reading assistant” workflows
    """

    max_chars: int | OutputHandle[int] = connect_field(
        default=50000, description="Truncate output to this many characters"
    )
    prefer_article: bool | OutputHandle[bool] = connect_field(
        default=True, description="Prefer <article> text when present"
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.safari.SafariPageText

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.safari
from nodetool.workflows.base_node import BaseNode


class SafariSelectionText(
    SingleOutputGraphNode[types.TextRef], GraphNode[types.TextRef]
):
    """

    Read the current text selection from the front Safari tab (via injected JavaScript).
    safari, browser, macos, automation

    Use cases:
    - Copy a highlighted passage into an LLM prompt
    - Turn selected text into a note/task
    - Summarize just the selected section of a page
    """

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.safari.SafariSelectionText

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()
