# This file is auto-generated by nodetool.dsl.codegen.
# Please do not edit this file manually.

# Instead, edit the node class in the source module and run the following commands to regenerate the DSL:
# nodetool package scan
# nodetool codegen

from pydantic import BaseModel, Field
import typing
from typing import Any
import nodetool.metadata.types
import nodetool.metadata.types as types
from nodetool.dsl.graph import GraphNode, SingleOutputGraphNode

import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.screen
from nodetool.workflows.base_node import BaseNode


class CaptureScreen(SingleOutputGraphNode[types.ImageRef], GraphNode[types.ImageRef]):
    """

    Capture screen content via PyObjC
    screen, automation, macos, media
    """

    whole_screen: bool | OutputHandle[bool] = connect_field(
        default=True, description="Capture the whole screen"
    )
    x: int | OutputHandle[int] = connect_field(
        default=0, description="X coordinate of the region to capture"
    )
    y: int | OutputHandle[int] = connect_field(
        default=0, description="Y coordinate of the region to capture"
    )
    width: int | OutputHandle[int] = connect_field(
        default=1920, description="Width of the region to capture"
    )
    height: int | OutputHandle[int] = connect_field(
        default=1080, description="Height of the region to capture"
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.screen.CaptureScreen

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()
