# This file is auto-generated by nodetool.dsl.codegen.
# Please do not edit this file manually.

# Instead, edit the node class in the source module and run the following commands to regenerate the DSL:
# nodetool package scan
# nodetool codegen

from pydantic import BaseModel, Field
import typing
from typing import Any
import nodetool.metadata.types
import nodetool.metadata.types as types
from nodetool.dsl.graph import GraphNode, SingleOutputGraphNode

import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.shortcuts
from nodetool.workflows.base_node import BaseNode


class ListShortcuts(SingleOutputGraphNode[list[str]], GraphNode[list[str]]):
    """

    List Shortcuts available on the current macOS user account via the `shortcuts` CLI.
    shortcuts, macos, automation, productivity

    Use cases:
    - Populate a UI dropdown of available shortcuts
    - Verify a shortcut exists before running it
    - Discover “building block” shortcuts for an agent
    """

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.shortcuts.ListShortcuts

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.shortcuts
from nodetool.workflows.base_node import BaseNode


class RunShortcut(
    SingleOutputGraphNode[
        nodetool.metadata.types.TextRef | nodetool.metadata.types.DocumentRef
    ],
    GraphNode[nodetool.metadata.types.TextRef | nodetool.metadata.types.DocumentRef],
):
    """

    Run an Apple Shortcut via the `shortcuts` CLI, with optional file/text input and captured output.
    shortcuts, macos, automation, productivity

    Use cases:
    - Trigger complex app automations built in Shortcuts (Mail, Finder, Home, etc.)
    - Provide a human-approval “gate” inside Shortcuts before side effects
    - Bridge AI workflows to native macOS actions without bespoke API code
    """

    OutputMode: typing.ClassVar[type] = (
        nodetool.nodes.apple.shortcuts.RunShortcut.OutputMode
    )
    DecodeErrors: typing.ClassVar[type] = (
        nodetool.nodes.apple.shortcuts.RunShortcut.DecodeErrors
    )

    shortcut: str | OutputHandle[str] = connect_field(
        default="", description="Shortcut name or identifier to run"
    )
    inputs: list[types.AssetRef] | OutputHandle[list[types.AssetRef]] = connect_field(
        default=PydanticUndefined,
        description="Optional files to pass into the shortcut as input",
    )
    input_text: str | OutputHandle[str] = connect_field(
        default="", description="Optional text input; passed as a temporary .txt file"
    )
    output_type: str | OutputHandle[str] = connect_field(
        default="public.plain-text",
        description="Shortcut output type as a UTI (e.g. public.plain-text, public.json)",
    )
    output_mode: nodetool.nodes.apple.shortcuts.RunShortcut.OutputMode = Field(
        default=nodetool.nodes.apple.shortcuts.RunShortcut.OutputMode.TEXT,
        description="Return output as text or as a stored document asset",
    )
    output_name: str | OutputHandle[str] = connect_field(
        default="shortcut-output.txt",
        description="Asset name when output_mode=document",
    )
    output_content_type: str | OutputHandle[str] = connect_field(
        default="text/plain", description="Asset content type when output_mode=document"
    )
    timeout_seconds: int | OutputHandle[int] = connect_field(
        default=120, description="Max time to allow the shortcut to run"
    )
    decode_errors: nodetool.nodes.apple.shortcuts.RunShortcut.DecodeErrors = Field(
        default=nodetool.nodes.apple.shortcuts.RunShortcut.DecodeErrors.REPLACE,
        description="How to handle output bytes decoding when output_mode=text",
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.shortcuts.RunShortcut

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()
