# This file is auto-generated by nodetool.dsl.codegen.
# Please do not edit this file manually.

# Instead, edit the node class in the source module and run the following commands to regenerate the DSL:
# nodetool package scan
# nodetool codegen

from pydantic import BaseModel, Field
import typing
from typing import Any
import nodetool.metadata.types
import nodetool.metadata.types as types
from nodetool.dsl.graph import GraphNode, SingleOutputGraphNode

import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.speech
from nodetool.workflows.base_node import BaseNode


class SayText(SingleOutputGraphNode[bool], GraphNode[bool]):
    """

    Speak text using macOS's built-in text-to-speech
    speech, automation, macos, accessibility

    Use cases:
    - Add voice notifications to workflows
    - Create audio feedback
    - Accessibility features
    """

    MacOSVoice: typing.ClassVar[type] = nodetool.nodes.apple.speech.MacOSVoice

    text: str | OutputHandle[str] = connect_field(
        default="", description="Text to be spoken"
    )
    rate: float | OutputHandle[float] = connect_field(
        default=175.0, description="Speaking rate (words per minute)"
    )
    volume: float | OutputHandle[float] = connect_field(
        default=1.0, description="Volume level (0.0 to 1.0)"
    )
    voice: nodetool.nodes.apple.speech.MacOSVoice = Field(
        default=nodetool.nodes.apple.speech.MacOSVoice.ALBERT,
        description="Voice identifier",
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.speech.SayText

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()
