# This file is auto-generated by nodetool.dsl.codegen.
# Please do not edit this file manually.

# Instead, edit the node class in the source module and run the following commands to regenerate the DSL:
# nodetool package scan
# nodetool codegen

from pydantic import BaseModel, Field
import typing
from typing import Any
import nodetool.metadata.types
import nodetool.metadata.types as types
from nodetool.dsl.graph import GraphNode, SingleOutputGraphNode

import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.spotlight
from nodetool.workflows.base_node import BaseNode


class SpotlightMetadata(
    SingleOutputGraphNode[dict[str, Any]], GraphNode[dict[str, Any]]
):
    """

    Read Spotlight metadata for a file using `mdls`.
    spotlight, metadata, macos, retrieval

    Use cases:
    - Fetch title/authors/kind for retrieved files
    - Inspect tags, content type, and dates
    - Build structured context for agents
    """

    file: types.AssetRef | OutputHandle[types.AssetRef] = connect_field(
        default=PydanticUndefined,
        description="File to inspect (usually from SpotlightSearch)",
    )
    keys: list[str] | OutputHandle[list[str]] = connect_field(
        default=PydanticUndefined,
        description="Optional mdls keys (e.g. ['kMDItemKind','kMDItemContentType']); empty means all",
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.spotlight.SpotlightMetadata

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.spotlight
from nodetool.workflows.base_node import BaseNode


class SpotlightSearch(
    SingleOutputGraphNode[list[types.AssetRef]], GraphNode[list[types.AssetRef]]
):
    """

    Search local files using macOS Spotlight (`mdfind`).
    spotlight, search, macos, retrieval

    Use cases:
    - Local RAG: find relevant docs before summarization/QA
    - Locate recently modified files by content/metadata
    - Retrieve assets by tags, kind, or filename patterns
    """

    query: str | OutputHandle[str] = connect_field(
        default="", description="Spotlight query (mdfind syntax)"
    )
    limit: int | OutputHandle[int] = connect_field(
        default=20, description="Maximum results to return"
    )
    only_in: str | OutputHandle[str] = connect_field(
        default="",
        description="Optional directory to constrain search to (passed to mdfind -onlyin)",
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.spotlight.SpotlightSearch

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()
