# This file is auto-generated by nodetool.dsl.codegen.
# Please do not edit this file manually.

# Instead, edit the node class in the source module and run the following commands to regenerate the DSL:
# nodetool package scan
# nodetool codegen

from pydantic import BaseModel, Field
import typing
from typing import Any
import nodetool.metadata.types
import nodetool.metadata.types as types
from nodetool.dsl.graph import GraphNode, SingleOutputGraphNode

import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.system
from nodetool.workflows.base_node import BaseNode


class EmptyTrash(SingleOutputGraphNode[bool], GraphNode[bool]):
    """

    Empty the macOS Trash.
    system, finder, macos, automation

    Use cases:
    - Clean up after batch file operations
    - Scheduled maintenance workflows
    - Free disk space automation
    """

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.system.EmptyTrash

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.system
from nodetool.workflows.base_node import BaseNode


class GetBatteryStatus(SingleOutputGraphNode[dict], GraphNode[dict]):
    """

    Get battery status information (percentage, charging state, time remaining).
    system, battery, macos, automation

    Use cases:
    - Conditional workflows based on battery level
    - Power-aware task scheduling
    - Battery monitoring and alerts
    """

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.system.GetBatteryStatus

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.system
from nodetool.workflows.base_node import BaseNode


class GetDarkMode(SingleOutputGraphNode[bool], GraphNode[bool]):
    """

    Check if macOS Dark Mode is currently enabled.
    system, appearance, macos, automation

    Use cases:
    - Sync workflow output colors with system theme
    - Conditional logic based on appearance mode
    - Accessibility-aware workflows
    """

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.system.GetDarkMode

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.system
from nodetool.workflows.base_node import BaseNode


class GetFrontmostApplication(SingleOutputGraphNode[str], GraphNode[str]):
    """

    Get the name of the currently frontmost (active) application.
    system, applications, macos, automation

    Use cases:
    - Context-aware workflows based on active app
    - Log which app user is working in
    - Conditional automation based on focus
    """

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.system.GetFrontmostApplication

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.system
from nodetool.workflows.base_node import BaseNode


class GetMuteState(SingleOutputGraphNode[bool], GraphNode[bool]):
    """

    Check if the system audio is currently muted.
    system, volume, macos, automation

    Use cases:
    - Check mute state before playing audio
    - Save and restore mute state in workflows
    """

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.system.GetMuteState

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.system
from nodetool.workflows.base_node import BaseNode


class GetSystemVolume(SingleOutputGraphNode[int], GraphNode[int]):
    """

    Get the current system audio output volume (0-100).
    system, volume, macos, automation

    Use cases:
    - Check volume before playing audio
    - Save and restore volume in workflows
    - Monitor volume level for accessibility
    """

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.system.GetSystemVolume

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.system
from nodetool.workflows.base_node import BaseNode


class ListRunningApplications(SingleOutputGraphNode[list[str]], GraphNode[list[str]]):
    """

    List all currently running applications.
    system, applications, macos, automation

    Use cases:
    - Check if an app is running before sending commands
    - Monitor active applications for workflows
    - Application discovery for automation
    """

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.system.ListRunningApplications

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.system
from nodetool.workflows.base_node import BaseNode


class OpenApplication(SingleOutputGraphNode[bool], GraphNode[bool]):
    """

    Launch or bring to front a macOS application.
    system, applications, macos, automation

    Use cases:
    - Open apps as part of a workflow
    - Bring an app to foreground for user interaction
    - Launch specific tools before automation steps
    """

    app_name: str | OutputHandle[str] = connect_field(
        default="", description="Name of the application to open"
    )
    activate: bool | OutputHandle[bool] = connect_field(
        default=True, description="Bring the application to the foreground"
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.system.OpenApplication

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.system
from nodetool.workflows.base_node import BaseNode


class QuitApplication(SingleOutputGraphNode[bool], GraphNode[bool]):
    """

    Quit a running macOS application.
    system, applications, macos, automation

    Use cases:
    - Clean up apps after workflow completion
    - Close apps before system sleep
    - Resource management automation
    """

    app_name: str | OutputHandle[str] = connect_field(
        default="", description="Name of the application to quit"
    )
    save_changes: bool | OutputHandle[bool] = connect_field(
        default=True, description="Prompt to save changes (if applicable)"
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.system.QuitApplication

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.system
from nodetool.workflows.base_node import BaseNode


class SetDarkMode(SingleOutputGraphNode[bool], GraphNode[bool]):
    """

    Enable or disable macOS Dark Mode.
    system, appearance, macos, automation

    Use cases:
    - Toggle dark mode on schedule
    - Switch appearance for presentations
    - Sync appearance with external lighting
    """

    enabled: bool | OutputHandle[bool] = connect_field(
        default=True, description="Enable dark mode"
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.system.SetDarkMode

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.system
from nodetool.workflows.base_node import BaseNode


class SetMuteState(SingleOutputGraphNode[bool], GraphNode[bool]):
    """

    Mute or unmute the system audio.
    system, volume, macos, automation

    Use cases:
    - Mute system during sensitive operations
    - Toggle mute for hands-free workflows
    """

    muted: bool | OutputHandle[bool] = connect_field(
        default=True, description="Set to True to mute, False to unmute"
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.system.SetMuteState

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.system
from nodetool.workflows.base_node import BaseNode


class SetSystemVolume(SingleOutputGraphNode[bool], GraphNode[bool]):
    """

    Set the system audio output volume (0-100).
    system, volume, macos, automation

    Use cases:
    - Mute system before TTS playback
    - Adjust volume for notifications
    - Automate volume for time-of-day workflows
    """

    volume: int | OutputHandle[int] = connect_field(
        default=50, description="Volume level (0-100)"
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.system.SetSystemVolume

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.system
from nodetool.workflows.base_node import BaseNode


class SleepDisplay(SingleOutputGraphNode[bool], GraphNode[bool]):
    """

    Put the display to sleep (without sleeping the whole system).
    system, display, macos, automation

    Use cases:
    - Save power when running unattended workflows
    - Quick privacy screen for leaving desk
    - Power management automation
    """

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.system.SleepDisplay

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()
