# This file is auto-generated by nodetool.dsl.codegen.
# Please do not edit this file manually.

# Instead, edit the node class in the source module and run the following commands to regenerate the DSL:
# nodetool package scan
# nodetool codegen

from pydantic import BaseModel, Field
import typing
from typing import Any
import nodetool.metadata.types
import nodetool.metadata.types as types
from nodetool.dsl.graph import GraphNode, SingleOutputGraphNode

import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.text_services
from nodetool.workflows.base_node import BaseNode


class DetectLanguage(SingleOutputGraphNode[str], GraphNode[str]):
    """

    Detect the dominant language of a text using CoreFoundation.
    language, text, macos, automation

    Use cases:
    - Route text to appropriate translation services
    - Language-aware content processing
    - Multi-language workflow branching
    """

    text: str | OutputHandle[str] = connect_field(
        default="", description="Text to analyze for language"
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.text_services.DetectLanguage

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.text_services
from nodetool.workflows.base_node import BaseNode


class SpellCheck(SingleOutputGraphNode[list[dict]], GraphNode[list[dict]]):
    """

    Check spelling in text using macOS spell checker.
    spelling, text, macos, automation

    Use cases:
    - Validate text before sending/publishing
    - Find typos in workflow inputs
    - Quality control for generated content
    """

    text: str | OutputHandle[str] = connect_field(
        default="", description="Text to spell check"
    )
    language: str | OutputHandle[str] = connect_field(
        default="en", description="Language code for spell checking (e.g., 'en', 'de')"
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.text_services.SpellCheck

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()
