# This file is auto-generated by nodetool.dsl.codegen.
# Please do not edit this file manually.

# Instead, edit the node class in the source module and run the following commands to regenerate the DSL:
# nodetool package scan
# nodetool codegen

from pydantic import BaseModel, Field
import typing
from typing import Any
import nodetool.metadata.types
import nodetool.metadata.types as types
from nodetool.dsl.graph import GraphNode, SingleOutputGraphNode

import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.vision
from nodetool.workflows.base_node import BaseNode


class OCRImage(SingleOutputGraphNode[types.TextRef], GraphNode[types.TextRef]):
    """

    Extract text from an image using Apple's Vision framework (VNRecognizeTextRequest).
    vision, ocr, macos, automation

    Use cases:
    - Screenshot → OCR → summarize / classify
    - Read text from receipts, dialogs, error messages
    - Turn UI text into reminders/notes/messages
    """

    RecognitionLevel: typing.ClassVar[type] = (
        nodetool.nodes.apple.vision.OCRImage.RecognitionLevel
    )

    image: types.ImageRef | OutputHandle[types.ImageRef] = connect_field(
        default=PydanticUndefined, description="Image to run OCR on"
    )
    recognition_level: nodetool.nodes.apple.vision.OCRImage.RecognitionLevel = Field(
        default=nodetool.nodes.apple.vision.OCRImage.RecognitionLevel.ACCURATE,
        description="OCR speed/accuracy tradeoff",
    )
    languages: list[str] | OutputHandle[list[str]] = connect_field(
        default=PydanticUndefined,
        description="Optional BCP-47 language codes (e.g. ['en-US','de-DE'])",
    )
    uses_language_correction: bool | OutputHandle[bool] = connect_field(
        default=True, description="Enable language correction"
    )
    min_confidence: float | OutputHandle[float] = connect_field(
        default=0.0, description="Drop recognized strings below this confidence"
    )
    join_with: str | OutputHandle[str] = connect_field(
        default="\n", description="How to join recognized lines into the output text"
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.vision.OCRImage

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()
