# This file is auto-generated by nodetool.dsl.codegen.
# Please do not edit this file manually.

# Instead, edit the node class in the source module and run the following commands to regenerate the DSL:
# nodetool package scan
# nodetool codegen

from pydantic import BaseModel, Field
import typing
from typing import Any
import nodetool.metadata.types
import nodetool.metadata.types as types
from nodetool.dsl.graph import GraphNode, SingleOutputGraphNode

import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.window_management
from nodetool.workflows.base_node import BaseNode


class CaptureScreen(SingleOutputGraphNode[types.ImageRef], GraphNode[types.ImageRef]):
    """

    Capture screen content via PyObjC
    screen, automation, macos, media
    """

    whole_screen: bool | OutputHandle[bool] = connect_field(
        default=True, description="Capture the whole screen"
    )
    x: int | OutputHandle[int] = connect_field(
        default=0, description="X coordinate of the region to capture"
    )
    y: int | OutputHandle[int] = connect_field(
        default=0, description="Y coordinate of the region to capture"
    )
    width: int | OutputHandle[int] = connect_field(
        default=1920, description="Width of the region to capture"
    )
    height: int | OutputHandle[int] = connect_field(
        default=1080, description="Height of the region to capture"
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.window_management.CaptureScreen

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.window_management
from nodetool.workflows.base_node import BaseNode


class CaptureWindow(SingleOutputGraphNode[types.ImageRef], GraphNode[types.ImageRef]):
    """

    Capture specific window by name or ID
    window, capture, automation, macos
    """

    window_name: str | OutputHandle[str] = connect_field(
        default="", description="Name of the window to capture"
    )
    window_id: int | OutputHandle[int] = connect_field(
        default=0, description="Window ID to capture (overrides name)"
    )
    owner_name: str | OutputHandle[str] = connect_field(
        default="", description="Application name that owns the window"
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.window_management.CaptureWindow

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.window_management
from nodetool.workflows.base_node import BaseNode


class FocusApplication(SingleOutputGraphNode[dict], GraphNode[dict]):
    """

    Bring an application to the foreground
    focus, application, automation, macos
    """

    application_name: str | OutputHandle[str] = connect_field(
        default=PydanticUndefined, description="Name of the application to focus"
    )
    bundle_id: str | OutputHandle[str] = connect_field(
        default="", description="Bundle ID of the application (overrides name)"
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.window_management.FocusApplication

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.window_management
from nodetool.workflows.base_node import BaseNode


class GetActiveWindow(SingleOutputGraphNode[dict], GraphNode[dict]):
    """

    Get information about the currently active window
    window, active, automation, macos
    """

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.window_management.GetActiveWindow

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.window_management
from nodetool.workflows.base_node import BaseNode


class GetScreenResolution(SingleOutputGraphNode[dict], GraphNode[dict]):
    """

    Get screen resolution and display information
    screen, display, system, macos
    """

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.window_management.GetScreenResolution

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.window_management
from nodetool.workflows.base_node import BaseNode


class GetWindowList(SingleOutputGraphNode[list[dict]], GraphNode[list[dict]]):
    """

    Get list of all open windows
    window, automation, macos, system
    """

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.window_management.GetWindowList

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.apple.window_management
from nodetool.workflows.base_node import BaseNode


class ListApplications(SingleOutputGraphNode[list[dict]], GraphNode[list[dict]]):
    """

    List all running applications
    applications, system, automation, macos
    """

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.apple.window_management.ListApplications

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()
